// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO9NV5c-V13lA63ujEIh8zO3CA2aA4s5M',
    appId: '1:674113833726:web:0a598f4d8760c84fdc73af',
    messagingSenderId: '674113833726',
    projectId: 'disciplan-57d36',
    authDomain: 'disciplan-57d36.firebaseapp.com',
    storageBucket: 'disciplan-57d36.firebasestorage.app',
    measurementId: 'G-RRYZHNMKZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtFHuUNaaigy2WvFcxN3PhcALX8IpoPE',
    appId: '1:674113833726:android:37f77c8b4723ebeedc73af',
    messagingSenderId: '674113833726',
    projectId: 'disciplan-57d36',
    storageBucket: 'disciplan-57d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRH10IhznTRrqoTqyUU2uKfXOAz2C1zsY',
    appId: '1:674113833726:ios:9fd78de5f8923340dc73af',
    messagingSenderId: '674113833726',
    projectId: 'disciplan-57d36',
    storageBucket: 'disciplan-57d36.firebasestorage.app',
    iosBundleId: 'com.example.disciplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRH10IhznTRrqoTqyUU2uKfXOAz2C1zsY',
    appId: '1:674113833726:ios:9fd78de5f8923340dc73af',
    messagingSenderId: '674113833726',
    projectId: 'disciplan-57d36',
    storageBucket: 'disciplan-57d36.firebasestorage.app',
    iosBundleId: 'com.example.disciplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO9NV5c-V13lA63ujEIh8zO3CA2aA4s5M',
    appId: '1:674113833726:web:1c53fa1d28ae29ebdc73af',
    messagingSenderId: '674113833726',
    projectId: 'disciplan-57d36',
    authDomain: 'disciplan-57d36.firebaseapp.com',
    storageBucket: 'disciplan-57d36.firebasestorage.app',
    measurementId: 'G-2J5G1LHSG8',
  );
}
